.TH "SocketBuild/ClientManager.cpp" 3 "Version 1.0.0" "ChatMultiServerDoxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketBuild/ClientManager.cpp \- \fBClientManager\&.h\fP 구현부\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'ClientManager\&.h'\fP
.br
\fR#include 'DebugHelper\&.h'\fP
.br

.SH "상세한 설명"
.PP 
\fBClientManager\&.h\fP 구현부\&. 


.PP
\fB작성자\fP
.RS 4
최성락 
.RE
.PP
\fB날짜\fP
.RS 4
2025-06-17 
.RE
.PP

.PP
\fBClientManager\&.cpp\fP 파일에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 ChatMultiServerDoxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
