.TH "SocketBuild/main.cpp" 3 "Version 1.0.0" "ChatMultiServerDoxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketBuild/main.cpp \- 멀티 클라이언트 서버 프로그램 main\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'DebugHelper\&.h'\fP
.br
\fR#include 'MemoryLeakHelper\&.h'\fP
.br
\fR#include 'Program\&.h'\fP
.br
\fR#include <Windows\&.h>\fP
.br
\fR#include <io\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br

.SS "함수"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "상세한 설명"
.PP 
멀티 클라이언트 서버 프로그램 main\&. 


.PP
\fB작성자\fP
.RS 4
최성락 
.RE
.PP
\fB날짜\fP
.RS 4
2025-06-17 
.RE
.PP

.PP
\fBmain\&.cpp\fP 파일에서 정의되었습니다\&.
.SH "함수 문서화"
.PP 
.SS "int main ()"

.PP
\fBmain\&.cpp\fP 파일의 \fB17\fP 번째 라인에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 ChatMultiServerDoxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
