.TH "SocketBuild/MessageReceiver.h" 3 "Version 1.0.0" "ChatMultiServerDoxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketBuild/MessageReceiver.h \- 클라이언트로부터 들어오는 메시지를 처리하는 \fBMessageReceiver\fP 클래스를 선언합니다\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <winsock2\&.h>\fP
.br
\fR#include <string>\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBMessageReceiver\fP"
.br
.RI "클라이언트 소켓으로부터 들어오는 메시지를 처리하는 클래스입니다\&. "
.in -1c
.SH "상세한 설명"
.PP 
클라이언트로부터 들어오는 메시지를 처리하는 \fBMessageReceiver\fP 클래스를 선언합니다\&. 


.PP
\fB작성자\fP
.RS 4
최성락 
.RE
.PP
\fB날짜\fP
.RS 4
2025-06-17
.RE
.PP
단일 클라이언트 소켓에서 메시지를 수신하고 파싱하는 역할을 담당합니다\&. 특정 명령(예: "quit")을 감지하고, 명령에 맞는 역할을 수행합니다\&. 
.PP
\fBMessageReceiver\&.h\fP 파일에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 ChatMultiServerDoxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
