.TH "SocketBuild/Program.h" 3 "Version 1.0.0" "ChatMultiServerDoxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketBuild/Program.h \- 채팅 서버 프로그램을 초기화하고 실행하는 클래스를 정의합니다\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'SocketIniter\&.h'\fP
.br
\fR#include 'MultiServer\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBProgram\fP"
.br
.RI "채팅 서버 프로그램의 시작, 실행 및 종료를 제어합니다\&. "
.in -1c
.SH "상세한 설명"
.PP 
채팅 서버 프로그램을 초기화하고 실행하는 클래스를 정의합니다\&. 


.PP
\fB작성자\fP
.RS 4
최성락 
.RE
.PP
\fB날짜\fP
.RS 4
2025-06-17
.RE
.PP
\fBProgram\fP 클래스는 프로그램의 시작과 종료를 캡슐화합니다\&. 
.br
WinSock을 초기화하고, MultiServer를 시작하며, 서버 루프를 실행합니다\&. 
.br
이 클래스는 \fRmain\fP 함수에서 전체적인 프로그램 흐름을 관리하는 데 사용됩니다\&. 
.PP
\fBProgram\&.h\fP 파일에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 ChatMultiServerDoxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
