.TH "SocketBuild/TCPSocket.h" 3 "Version 1.0.0" "ChatMultiServerDoxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketBuild/TCPSocket.h \- TCP 리스닝 소켓을 제어하는 \fBTCPSocket\fP 클래스를 선언합니다\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <WinSock2\&.h>\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBTCPSocket\fP"
.br
.RI "TCP 서버 소켓과 그 기본 동작(생성, 바인드, 연결 대기, 연결 수락, 종료)을 캡슐화합니다\&. "
.in -1c
.SH "상세한 설명"
.PP 
TCP 리스닝 소켓을 제어하는 \fBTCPSocket\fP 클래스를 선언합니다\&. 


.PP
\fB작성자\fP
.RS 4
최성락 
.RE
.PP
\fB날짜\fP
.RS 4
2025-06-17
.RE
.PP
\fBTCPSocket\fP 클래스는 소켓 생성, 포트 바인딩, 연결 대기, 클라이언트 수락, 소켓 종료와 같은 서버 소켓 설정 작업을 수행하는 메서드들을 제공합니다\&. 
.br
이를 통해 저수준의 소켓 호출을 단순한 인터페이스로 추상화할 수 있습니다\&. 
.PP
\fBTCPSocket\&.h\fP 파일에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 ChatMultiServerDoxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
